### ISSUE TITLE
Can`t create a conversation.

### ISSUE THREAD

**Issue by KovaliovNA** [MicrosoftDocs/bot-docs.ru-ru#1]
I trying to create a new conversation with person or group of persons, so I create a Bearer token for authentication and add it to header as bearer token (in postman).

So on the next step I create a json script that, theoretically, can create a new conversation. I trying to create a conversation with several person or with only one (for it I added a several person to members or one and change flag isGroup to true or false).

This is a example of json for 1 person:

{
    "bot": {
        "id": "<app id>",
        "name": "<bot name>"
    },
    "isGroup": false,
    "members": [
       {
            "id": "<member id>",
            "name": "<member name>"
        }
    ],
    "topicName": "Hello there!"
}
Member id is correct for all members that I trying to add in a new conversation.

And the next response I get always:

{
    "id": "8:live:<skype account name>"
}
For group conversation I get the this live skype name for first person that I added. All requests was send to https://skype.botframework.com/v3/conversations or https://smba.trafficmanager.net/apis/v3/conversations and response always same.

Also I trying add a activity into request and bot send the message just for first member in list.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [Справочник по API - Bot Service](https://docs.microsoft.com/ru-ru/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs.ru-ru/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
Hello, @KovaliovNA

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
